-- ============================================================
-- PLAN ONLY. Do not execute against production database.
-- Requires manual review before execution.
-- ============================================================
-- VC v3 Platform Contracts — Testnet D1 Insert Plan
-- Generated: (pending deployment)
-- ============================================================
-- Purpose:
--   Insert SaleVesting and TeamVesting testnet addresses
--   into the platform_contracts table AFTER deployment.
--   Existing six platform contract rows are NOT modified.
-- ============================================================

-- ============================================================
-- SALE_VESTING
-- Execute after SaleVesting is deployed and address confirmed:
-- ============================================================
-- INSERT OR REPLACE INTO platform_contracts (contract_name, network, address, created_at)
-- VALUES ('SALE_VESTING', 'testnet', '<FILL_AFTER_DEPLOY>', datetime('now'));

-- ============================================================
-- TEAM_VESTING
-- Execute after TeamVesting is deployed and address confirmed:
-- ============================================================
-- INSERT OR REPLACE INTO platform_contracts (contract_name, network, address, created_at)
-- VALUES ('TEAM_VESTING', 'testnet', '<FILL_AFTER_DEPLOY>', datetime('now'));

-- ============================================================
-- Verification queries (read-only, safe to run):
-- ============================================================
-- SELECT contract_name, network, address FROM platform_contracts
-- WHERE network = 'testnet' ORDER BY contract_name;
