[package]
name = "vibecoder-contracts"
description = "A TON blockchain project"
version = "0.1.0"
license = "MIT"

[contracts.early_fundraising]
display-name = "Early Fundraising"
src = "contracts/platform/token-system/early-fundraising/early_fundraising.tolk"
depends = []

[contracts.developer_reward_pool]
display-name = "Developer Reward Pool"
src = "contracts/platform/token-system/developer-reward-pool/developer_reward_pool.tolk"
depends = []

[contracts.development_fund]
display-name = "Development Fund"
src = "contracts/platform/token-system/development-fund/development_fund.tolk"
depends = []

[contracts.ecosystem_reward_pool]
display-name = "Ecosystem Reward Pool"
src = "contracts/platform/token-system/ecosystem-reward-pool/ecosystem_reward_pool.tolk"
depends = []

[contracts.fund]
display-name = "Fund"
src = "contracts/platform/token-system/fund/fund.tolk"
depends = []

[contracts.launch_campaign]
display-name = "Launch Campaign"
src = "contracts/launch/launch-campaign/launch_campaign.tolk"
depends = []

[contracts.launch_fee]
display-name = "Launch Fee"
src = "contracts/platform/token-system/launch-fee/launch_fee.tolk"
depends = []

[contracts.project_token]
display-name = "Project Token"
src = "contracts/launch/project-token/project_token.tolk"
depends = []

[contracts.project_token_wallet]
display-name = "Project Token Wallet"
src = "contracts/launch/project-token/project_token_wallet.tolk"
depends = []

[contracts.reserve_vault]
display-name = "Reserve Vault"
src = "contracts/platform/token-system/reserve-vault/reserve_vault.tolk"
depends = []

[contracts.sale_vesting]
display-name = "Sale Vesting"
src = "contracts/platform/token-system/sale-vesting/sale_vesting.tolk"
depends = []

[contracts.simple_launch_campaign]
display-name = "Simple Launch Campaign"
src = "contracts/launch/simple-launch/simple_launch_campaign.tolk"
depends = []

[contracts.launch_escrow]
display-name = "Launch Escrow"
src = "contracts/launch/simple-launch/launch_escrow.tolk"
depends = []

[contracts.team_vesting]
display-name = "Team Vesting"
src = "contracts/platform/token-system/team-vesting/team_vesting.tolk"
depends = []

[contracts.token_launcher]
display-name = "Token Launcher"
src = "contracts/platform/infra/token-launcher/token_launcher.tolk"
depends = []

[contracts.vc_jetton]
display-name = "Vc Jetton"
src = "contracts/platform/token-system/vc-jetton/vc_jetton.tolk"
depends = []

[contracts.vc_reward_pool]
display-name = "VC Reward Pool"
src = "contracts/platform/token-system/vc-reward-pool/vc_reward_pool.tolk"
depends = []

[contracts.vesting]
display-name = "Vesting"
src = "contracts/launch/vesting/vesting.tolk"
depends = []

[fmt]
width = 100
ignore = []

[import-mappings]
acton = ".acton"
contracts = "contracts"
gen = "gen"
tests = "tests"
wrappers = "wrappers"
