name = "vibecoder-api"
main = "src/index.ts"
compatibility_date = "2024-02-22"
compatibility_flags = [ "nodejs_compat" ]
account_id = "ff431aed46e94b0593b8b1ee48842c7a"

[[d1_databases]]
binding = "DB"
database_name = "vibecoder-db-new"
database_id = "0e70b6ab-875e-44a9-a3a6-dd84d7eaf1f2"
migrations_dir = "migrations"

[vars]
TON_NETWORK = "testnet"
ENVIRONMENT = "development"

routes = [
  "api.72h.lol/*",
]

[[services]]
binding = "SIGNER_SERVICE"
service = "vibecoder-signer"
